[project]
name = "spotify-player-rpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
    "rpi-gpio>=0.7.1",
    "smbus2>=0.5.0",
    "spotipy>=2.25.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true 

[tool.mypy.overrides]
module = [
    "rgbmatrix",
    "spotify_player_rpi",
]
ignore_missing_imports = true